title: "Question: "
labels: ["question",]
body:
  - type: markdown
    attributes:
      value: |
        <!--- Logo and Header -->
        <div align="center">  
        <picture>
          <source media="(prefers-color-scheme: dark)" srcset="https://github.com/Lennolium/PrivacyShield/raw/master/img/banner_dark.png" 
        width="500vw">
          <source media="(prefers-color-scheme: light)" 
        srcset="https://github.com/Lennolium/PrivacyShield/raw/master/img/banner_light.png" 
        width="500vw">
          <img alt="PrivacyShield Banner" src="https://github.com/Lennolium/PrivacyShield/raw/master/img/banner_light.png" 
        width="500vw">
        </picture>
        </div>
        
        <h2 align="center">Question Submit Form</h2>
        <div align="center">
          Provide the following information properly, which will help me to answer your question quickly. 
          If you need further help with this form, please do not hesitate and contact me via <a href="mailto:privacyshield@lennolium.dev">email</a>.
          Also make sure to check the the discussion forum for similar questions before submitting this form to avoid duplicates.
          Also consider, that if you have a question about a specific website, you should use the <a href="https://github.com/Lennolium/PrivacyShield/issues/new?assignees=Lennolium&labels=false+positive&projects=&template=1-false-negative.yml&title=False-Positive%3A+example.org">False-Positive Submit Form</a> instead.
          For issues regarding the filter lists, please open a new issue in the <a href="https://github.com/Lennolium/PrivacyShield/issues/new/choose">Issues tab</a>. 
          For all general questions, please use this form.
          <br>
          <br>
        
          <a href="https://github.com/Lennolium/PrivacyShield/discussions" > 
            <img src="https://img.shields.io/github/discussions/Lennolium/PrivacyShield?style=flat-square&color=deepskyblue" alt="discussions" >
          </a>
        
        </div>
        <br>
        <br>


  - type: dropdown
    id: category
    attributes:
      label: Category
      description: About what do you have a question?
      options:
        - Installation of PrivacyShield
        - Features/Functionality
        - Included Lists
        - Future Plans
        - Development/Contributing
        - Other
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br>

  - type: textarea
    id: question
    attributes:
      label: Question
      description: Here you ask your specific question and provide detailed information. You can also attach screenshots and files here.
      placeholder: I have a question ...

  - type: markdown
    attributes:
      value: |
        <br>

  

  - type: markdown
    attributes:
      value: |
        <br>

  - type: textarea
    id: other-info
    attributes:
      label: Further Information
      description: Feel free to add any further information maybe needed here.
      render: shell

  - type: markdown
    attributes:
      value: |
        <br>

  - type: checkboxes
    id: terms
    attributes:
      label: Agreements
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Lennolium/PrivacyShield/blob/master/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
        - label: I confirm that I have searched the issue and discussion tab for similar questions and this is not a duplicate.
          required: true
