name: "\U0001F41B Report a False-Positive"
description: "You found a not-working or wrongly blocked website"
title: "False-Positive: example.org"
labels: ["false positive",]
assignees:
  - Lennolium
body:
  - type: markdown
    attributes:
      value: |
        <!--- Logo and Header -->
        <div align="center">  
        <picture>
          <source media="(prefers-color-scheme: dark)" srcset="https://github.com/Lennolium/PrivacyShield/raw/master/img/banner_dark.png" 
        width="450vw">
          <source media="(prefers-color-scheme: light)" 
        srcset="https://github.com/Lennolium/PrivacyShield/raw/master/img/banner_light.png" 
        width="450vw">
          <img alt="PrivacyShield Banner" src="https://github.com/Lennolium/PrivacyShield/raw/master/img/banner_light.png" 
        width="450vw">
        </picture>
        </div>
        <br>
        
        <h2 align="center">False-Positive Submit Form</h2>
        <div align="center">
          Provide the following information properly, which will help me to resolve your issue, add the website to the whitelist and remove it from the filter lists quickly.
          If you need further help with this form, please do not hesitate and contact me via <a href="mailto:privacyshield@lennolium.dev">email</a>.
        </div>
        <br>

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What kind of issue are you reporting?
      options:
        - Good website blocked
        - Website functionality broken
        - Image(s) not showing
        - Mobile app blocked
        - Other
      default: 0
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Domain
      description: What is the domain/url of the website you are reporting?
      placeholder: example.org
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: If you want to be contacted outside of GitHub, please provide your email address.
      placeholder: email@example.com
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Lennolium/PrivacyShield/blob/master/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
