name: "\U0001F41B Report a General Issue"
description: "For all general issues regarding the filter lists"
title: "General: "
labels: ["general issue",]
assignees:
  - Lennolium
body:
  - type: markdown
    attributes:
      value: |
        <!--- Logo and Header -->
        <div align="center">  
        <picture>
          <source media="(prefers-color-scheme: dark)" srcset="https://github.com/Lennolium/PrivacyShield/raw/master/img/banner_dark.png" 
        width="500vw">
          <source media="(prefers-color-scheme: light)" 
        srcset="https://github.com/Lennolium/PrivacyShield/raw/master/img/banner_light.png" 
        width="500vw">
          <img alt="PrivacyShield Banner" src="https://github.com/Lennolium/PrivacyShield/raw/master/img/banner_light.png" 
        width="500vw">
        </picture>
        </div>
        
        <h2 align="center">General Issue Submit Form</h2>
        <div align="center">
          Provide the following information properly, which will help me to resolve your issue quickly.
          If you need further help with this form, please do not hesitate and contact me via <a href="mailto:privacyshield@lennolium.dev">email</a>.
          Also make sure to check the issues tab for similar issues before submitting this form to avoid duplicates. 
          For False-Positives or requesting a website to be added to the lists, please open a respective issue in the <a href="https://github.com/Lennolium/PrivacyShield/issues/new/choose">Issues tab</a>.
          <br>
          <br>
        
          <a href="https://github.com/Lennolium/PrivacyShield/issues" > 
            <img src="https://img.shields.io/github/issues-raw/Lennolium/PrivacyShield?style=flat-square&label=Open%20Issues&color=deepskyblue" alt="open issues" >
          </a>
        
          <a href="https://github.com/Lennolium/PrivacyShield/issues?q=is%3Aissue+is%3Aclosed" > 
            <img src="https://img.shields.io/github/issues-closed-raw/Lennolium/PrivacyShield?style=flat-square&label=Closed%20Issues&color=aliceblue" alt="closed issues" >
          </a>  
        
        </div>
        <br>
        <br>

  - type: input
    id: category
    attributes:
      label: Category
      description: What kind of issue are you reporting?
      placeholder: Crash, Bug, Connection-Errors, ...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br>

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Also tell us briefly about the issue and provide all necessary information. You can also attach screenshots and files here.
      placeholder: I'm facing an issue with ...

  - type: markdown
    attributes:
      value: |
        <br>

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using? (e.g. Windows, macOS, Linux, Android, iOS, ...)
      placeholder: Operating System name and version
    validations:
      required: true


  - type: markdown
    attributes:
      value: |
        <br>

  - type: input
    id: adblocker
    attributes:
      label: AdBlocker
      description: Which AdBlocker are you using? (e.g. Pi-Hole, AdGuard Home, AdBlock, ...)
      placeholder: Application name and version
    validations:
      required: true


  - type: markdown
    attributes:
      value: |
        <br>

  - type: dropdown
    id: list
    attributes:
      label: Which List(s) are you using?
      description: You can select multiple lists from the dropdown below.
      multiple: true
      options:
        - Bronze/Mobile
        - Silver
        - Gold
        - Platinum
        - Diamond
        - Antimatter
        - Domains-only
        - Hosts
        - Whitelist
        - Not applicable
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br>

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version are you running? You can find it in the header of the list file.
      options:
        - Latest (2.0.0)
        - 1.1.1
        - 1.1.0
        - 1.0.0
        - Legacy
        - Not applicable
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br>

  - type: textarea
    id: other-info
    attributes:
      label: Further Information
      description: Please paste any further information maybe needed here.
      render: shell

  - type: markdown
    attributes:
      value: |
        <br>

  - type: checkboxes
    id: terms
    attributes:
      label: Agreements
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Lennolium/PrivacyShield/blob/master/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
        - label: I confirm that I have searched the issue tracker for similar issues and this is not a duplicate.
          required: true
